### ISSUE TITLE
Static Files

### ISSUE THREAD

**Issue by oscarmcm** [mtigas/django-medusa#17]
Hey, I'm using django-medusa for a project, by the time the render is fine, but can not do anything with static files (css, js, img), you know some way to make the render take this files?

**Comment by jlev** [comment]
@oscarmcm You can use the collectstatic command to copy all the css, js, img files to the output directory. You may need to change STATIC_ROOT in settings.py to equal MEDUSA_DEPLOY_DIR.

**Comment by alsoicode** [comment]
I'm temporarily handling this by adding a `medusa_settings.py` file to change `STATIC_ROOT` to my destination directory. Since I typically put all of my static files into a directory called "static" this equates to:

    from .settings import *

    STATIC_ROOT = 'build-destination-directory/static'

Then I can collect static files, ignoring ones used by Django admin via:

    $ python manage.py collectstatic --settings=my_app.medusa_settings -i admin -i less -i whatever

I'm going to look at adding a call to `collectstatic` at the end of the `staticsitegen` command for convenience, since you'd typically deploy to your server from the destination directory and it's just nicer to have everything in the same place, imo.

**Comment by alsoicode** [comment]
@oscarmcm See my branch: https://github.com/alsoicode/django-medusa which adds static file collection.

**Comment by oscarmcm** [comment]
@jlev  @alsoicode hey thanks for sharing and helping, yes, at the end I did something similar but create a render and an importer who are responsible for rendering the view to a static pages and import the static files to a directory specified in the settings. very grateful for your help.
